### ISSUE TITLE
Insert Navbar

### ISSUE THREAD

**Issue by kavya1526** [MSTC-DA-IICT/B-for-Blog#1]
Create a new file in 'templates' folder - layout.html Add a navbar and a footer in this page.

The navbar should include hyperlinks to:
- Home page
- Login page
- Create blog
- Logout

This navbar will be later customized for every page using Django Template Language.

The footer must contain at least the site title - 'B for Blog'. Other component(s) may be added as per the contributor's ideas.

**Comment by Anik-Bardhan** [comment]
@kavya1526 Can I be assigned to this?

**Comment by kavya1526** [comment]
Assigned the issue to @Anik-Bardhan
