### ISSUE TITLE
Shift URL Patterns from Django Project to Django App

### ISSUE THREAD

**Issue by dishantvyas15** [MSTC-DA-IICT/B-for-Blog#14]
Issue:
All the existing patterns belong to the django project folder and not the django app folder.

Solution:
Create a `urls.py` file in the `blog` app and move all the existing URL patterns from `django_blog/urls.py` to `blog/urls.py`. Include the URLs of  `blog/urls.py` in `django_blog/urls.py`.

**Comment by gkydev** [comment]
Hi can you assign this to me ?

**Comment by RahulPalve** [comment]
@dishantvyas15  Done #15

**Comment by dishantvyas15** [comment]
> @dishantvyas15 Done #15
We appreciate your work @RahulPalve but unfortunately, this violates our contribution guidelines. Contributors should initiate a pull request only after they're assigned the corresponding issue. You may get some other issue assigned to you and then work on it. Thanks.

**Comment by dishantvyas15** [comment]
> Hi can you assign this to me ?
Sure @gkydev! Assigned to you.

**Comment by RahulPalve** [comment]
@dishantvyas15 Oh, I forgot to read guidelines, @gkydev you can start working my using my branch

**Comment by dishantvyas15** [comment]
> @dishantvyas15 Oh, I forgot to read guidelines, @gkydev you can start working my using my branch
Commend the spirit, @RahulPalve
