### ISSUE TITLE
Create and add logo

### ISSUE THREAD

**Issue by kavya1526** [MSTC-DA-IICT/B-for-Blog#2]
Create a simple and attractive logo for 'B for Blog' and add it at the top of the home page.

**Comment by kamalrt11** [comment]
I'd like to work on this issue.

**Comment by dishantvyas15** [comment]
Issue assigned to @kamalrt11 
Thanks.

**Comment by CoHarsh** [comment]
Hey! Can I also work on this Logo?
I am interested in this.

**Comment by dishantvyas15** [comment]
> Hey! Can I also work on this Logo? I am interested in this.

@CoHarsh, we appreciate your willingness to contribute, but each issue should have only one assignee. Please take up some other issue to work on.
