### ISSUE TITLE
[Bug] Registration form overlaps navbar

### ISSUE THREAD

**Issue by dishantvyas15** [MSTC-DA-IICT/B-for-Blog#27]
**Bug Desciption**
The registration form on the `registration.html` page is seen to be overlapping on the navbar.

**To Reproduce**
1. Start the Django server by running `py manage.py runserver` in the root directory.
2. Visit `/registration`

**Expected behavior**
The registration form should be well spaced from the navbar. You may see the `login` page for reference.

**Screenshot**
![image](https://user-images.githubusercontent.com/54072449/137613742-79716ebc-2792-4168-9573-53a59d0f11b3.png)

**Comment by rushil180101** [comment]
I would like to work on this issue.

**Comment by ayushkr7** [comment]
Hi, I would like to work on this issue.

**Comment by dishantvyas15** [comment]
Sure @ayushkr7. Go on.
