### ISSUE TITLE
Adding Links to Navbar

### ISSUE THREAD

**Issue by kavya1526** [MSTC-DA-IICT/B-for-Blog#3]
- Add hyperlinks to features of home,login,create blog, read blog that already exist to their corresponding pages

**Comment by Ronak-Jethava** [comment]
@kavya1526 
Can I be assigned to this task ?

**Comment by kavya1526** [comment]
@Ronak-Jethava This issue is assigned to you.

**Comment by mugdha273** [comment]
Hey, I'm willing to work on this issue if it's still needed.

**Comment by dishantvyas15** [comment]
Hey @mugdha273, we recognized this issue to be a redundant one and hence, are closing it. We will soon be opening new issues with the `up-for-grab` tag. You may get one of them assigned to you.
Thanks.

**Comment by dishantvyas15** [comment]
> Hey @mugdha273, we recognized this issue to be a redundant one and hence, are closing it. We will soon be opening new issues with the `up-for-grab` tag. You may get one of them assigned to you. Thanks.

The same message goes for @Ronak-Jethava as well.
