### ISSUE TITLE
Registration page and Linking

### ISSUE THREAD

**Issue by kavya1526** [MSTC-DA-IICT/B-for-Blog#6]
- Create a registration HTML page in the 'templates' folder.
- Create a view that returns this page on GET request.
- Set up a URL linked to this view in the urls.py file.
- Assure that 'Register here' button from login page leads here

**Comment by Ronak-Jethava** [comment]
@kavya1526 
I want to do this task, can I be assigned to it ?

**Comment by kavya1526** [comment]
@Ronak-Jethava At a given time, we will assign only one issue to one person.

**Comment by Ronak-Jethava** [comment]
Okay

**Comment by Tgb1801** [comment]
@kavya1526  I would like to work on this issue, can I be assigned to it?

**Comment by ParmarKrishna** [comment]
Can I work on this issue?

**Comment by kavya1526** [comment]
Issue assigned to @Tgb1801 based on first come,first served
@ParmarKrishna We appreciate your willingness to contribute. We request you to take up any other pending issue.

**Comment by ParmarKrishna** [comment]
alright. No problem!
