### ISSUE TITLE
Checking a successful login

### ISSUE THREAD

**Issue by kavya1526** [MSTC-DA-IICT/B-for-Blog#8]
- When user clicks on 'Login' button on login page, check whether the user already exists in database by checking the corresponding email and password.
- If it exists, redirect to home page
- Else display message 'Account does not exist. Click on register here'

**Comment by Tgb1801** [comment]
@kavya1526 I would like to work on this issue, can I be assigned to it?

**Comment by algo-geek** [comment]
@kavya1526 can I be assigned to work on the issue ?
